### ISSUE TITLE
request: conda-forge feedstock

### ISSUE THREAD

**Issue by kevinyamauchi** [spatial-image/spatial-image#18]
Hello, @thewtex ! I hope all is well. We are hoping to make [spatialdata ](https://github.com/scverse/spatialdata) available via conda-forge and we depend on `spatial-image` and `multiscale-spatial-image`. Would you be open to making `spatial-image` and `multiscale-spatial-image` available on conda-forge? If you are, I could make the PR to make the feedstock to the conda-forge recipes repo and add you as the maintainer. Would that be okay?

Thanks for the great library!

**Comment by kevinyamauchi** [comment]
Hey @thewtex ! Great! I am pretty slammed this week, but I will give it a go next week.

**Comment by thewtex** [comment]
@kevinyamauchi thank you!

**Comment by thewtex** [comment]
Feedstock is here: https://github.com/conda-forge/spatial-image-feedstock
