### ISSUE TITLE
Use xarray-dataclasses?

### ISSUE THREAD

**Issue by TomNicholas** [spatial-image/spatial-image#7]
Hi, I was just wondering if you had seen [xarray-dataclasses](https://github.com/astropenguin/xarray-dataclasses)? It seems like you could potentially do everything you're doing in this repo using that.

Separately if you want to attach your verification/conversion functions to xarray objects you can do that using [xarray's accessors](https://xarray.pydata.org/en/stable/internals/extending-xarray.html). Then you could have syntax like `da.si.to_spatial_image()`.

**Comment by thewtex** [comment]
xref https://github.com/spatial-image/spatial-image-multiscale/issues/8
